---
name: Label Issues
on:
  issues:
    types:
      - opened
jobs:
  label_issues_bugs:
    if: github.repository_owner == 'KelvinTegelaar' && contains(github.event.issue.title, 'Bug')
    runs-on: ubuntu-slim
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "not-assigned"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  label_issues_frs:
    if: github.repository_owner == 'KelvinTegelaar' && contains(github.event.issue.title, 'Feature')
    runs-on: ubuntu-slim
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "enhancement, not-assigned"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
