---
name: NodeJS Project Check
on:
  pull_request:
    branches:
      - main
      - dev
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: false
jobs:
  install-build:
    if: github.repository_owner == 'KelvinTegelaar'
    name: NPM Install and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.13.0"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Build Test
        run: |
          npm install --legacy-peer-deps
          npm run build
        env:
          CI: true
